lab-experiment-tracker/config/routes.rb
Rails.application.routes.draw do

  resources :proposals do
    resources :comments
    resources :experiments
  end

  resources :experiments do
    resources :comments
    resources :observations
    resources :procedures do
      resources :equipments
    end
  end

  resources :observations do
    resources :comments
  end

  resources :comments


  root 'proposals#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/signup' => 'users#new'
  get '/users/:id' => 'users#show'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  put '/proposals/:id' => 'proposals#update', :as => 'change_status'

end

lab-experiment-tracker/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

lab-experiment-tracker/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

lab-experiment-tracker/app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :procedure
end

lab-experiment-tracker/app/models/experiment.rb
class Experiment < ApplicationRecord
  belongs_to :proposal
  belongs_to :scientist, class_name: "User"
  
  has_many :procedures
  has_many :comments, as: :commentable
  has_many :observations, as: :observational

end

lab-experiment-tracker/app/models/observation.rb
class Observation < ApplicationRecord
  belongs_to :scientist, class_name: "User"
  belongs_to :observational, polymorphic: true
  has_many :comments, as: :commentable
end

lab-experiment-tracker/app/models/procedure.rb
class Procedure < ApplicationRecord
  belongs_to :experiment
  has_many :equipments
  has_many :comments, as: :commentable
  has_many :observations, as: :observational

  def gather_equipment(list)
    all_equipment = list.split(",").collect{|s| s.strip.downcase}.uniq
    all_equipment.each do |equipment|
      self.equipments << Equipment.create(description: equipment, procedure_id: self.id)
    end
  end

end

lab-experiment-tracker/app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :user
  has_many :experiments
  has_many :comments, as: :commentable

  def get_status
    if self.status == 1
      "Open"
    elsif self.status == 2
      "In progress"
    elsif self.status == 3
      "Closed"
    else
      "Archived"
    end
  end


end

lab-experiment-tracker/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :proposals
end

lab-experiment-tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ApplicationHelper
end

lab-experiment-tracker/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  include CommentsHelper
  include ApplicationHelper

  def index
  end

  def new
  end

  def create

    @object = request.fullpath.split("/")[1][0..-2].capitalize.constantize.find(request.fullpath.split("/")[2]).comments.create(body: params[:comment][:body], user_id: current_user.id)

    redirect_to(:back)
  end

end

lab-experiment-tracker/app/controllers/equipments_controller.rb
class CommentsController < ApplicationController

  include CommentsHelper
  include ApplicationHelper

  def index
    
  end


end

lab-experiment-tracker/app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  def new
    render 'experiments/_new.html.erb'
  end
  def create
    @proposal = Proposal.find(proposal_params)
    @experiment = Experiment.new(experiment_params)
    @experiment.scientist_id = current_user.id
    @experiment.proposal_id = @proposal.id

    @experiment.save
    @proposal.put_in_progress
    
    redirect_to proposal_path(@proposal)
  end

  def show
    @experiments = Experiment.all
    @experiment = Experiment.find(params[:id])

  end

  def update
    @experiment = Experiment.find(params[:id])
    @experiment.update(experiment_params)

    redirect_to (:back)
  end

  private
  def experiment_params
    params.require(:experiment).permit(:title, :results, :conclusions)
  end

  def proposal_params
    params.require(:proposal_id).to_i
  end
end

lab-experiment-tracker/app/controllers/observations_controller.rb
class ObservationsController < ApplicationController

  include CommentsHelper
  include ApplicationHelper

  def index
  end

  def new
  end

  def create
    
    @object = request.fullpath.split("/")[1][0..-2].capitalize.constantize.find(request.fullpath.split("/")[2]).observations.create(body: params[:observation][:body], scientist_id: current_user.id)

    redirect_to(:back)
  end

end

lab-experiment-tracker/app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
	def create
		@experiment = Experiment.find(experiment_params)
		@procedure = Procedure.new(body: params[:procedure][:body])
		@procedure.experiment_id = @experiment.id

		@procedure.save
		@procedure.gather_equipment(params[:procedure][:equipment])
		
		redirect_to experiment_path(@experiment)
	end

	private
	def experiment_params
		params.require(:experiment_id).to_i
	end

	# def procedure_params
	# 	params.require(:procedure).permit(:body)
	# end
end

lab-experiment-tracker/app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController

  def index

    #@proposal = Proposal.create(summary: "sdlkhflkadsj", hypothesis: "sdfadsf", user: User.first)
    #@comment = @proposal.comments.new
    @user = User.new
  	@proposals = Proposal.all
    @proposal = Proposal.new

  end

  def new
    @proposal = Proposal.new
  end

  def show
    @proposal = Proposal.find(params[:id])
    @comment = @proposal.comments
    @experiments = @proposal.experiments
    @status = @proposal.get_status
  end

  def create
    @proposal = Proposal.new(proposal_params)

    @proposal.user_id = session[:user_id]

    if @proposal.save
      redirect_to @proposal, notice: 'Proposal was successfully created.'
    else
      render :show, status: 422
    end
  end

  def update
    @proposal = Proposal.find(params[:id])
    @status = @proposal.get_status

    if @status == "Open"
      @proposal.update_attributes(status: 2)
    elsif @status == "In progress"
      @proposal.update_attributes(status: 3)
    elsif @status == "Closed"
      @proposal.update_attributes(status: 4)
    end
    @proposal.save
    redirect_to(:back)
  end

private
  def proposal_params
    params.require(:proposal).permit(:summary, :hypothesis)
  end

end

lab-experiment-tracker/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

 def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

 def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

lab-experiment-tracker/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

 def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end


 private

   def user_params
      params.require(:user).permit(:first_name, :last_name, :isScientist, :email, :password)
   end

end

lab-experiment-tracker/app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

 def logged_in?
    current_user ? true : false
  end

 def login
    session[:user_id] = @user.id
  end

 def logout
    session.clear
  end

 def authorize
    redirect_to '/login' unless current_user
  end

end

lab-experiment-tracker/app/helpers/comments_helper.rb
module CommentsHelper

  def comments_params
    params.require(:comment).permit(:body)
  end

end

lab-experiment-tracker/app/helpers/procedures_helper.rb
module ProceduresHelper
end

lab-experiment-tracker/app/views/comments/_new.html.erb
<div class="container blue darken-4">
  <div class="row">

    <%= form_for [commentable, comment]  do |f| %>

      <div class="col s12">
        <div class="row">
          <div class="input-field col s12">
              <%= f.label :body %>
              <%= f.text_field :body %><br />
            </div>
          </div>
          <%= submit_tag "Submit", :class => "waves-effect waves-light btn" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

lab-experiment-tracker/app/views/equipments/_index.html.erb
<ul class="equipment" style="display: none" >
  <% procedure.equipments.each do |equipment| %>
    <li><%= equipment.description %></li>
  <% end %>
</ul>

lab-experiment-tracker/app/views/experiments/_edit_conclusions.html.erb
<br>
<%= form_for :experiment, url: experiment_path(experiment), method: :put do |f| %>
  <%= f.text_area :conclusions %><br>
<br>

<%= f.submit "Update Experiment" %>
<% end %>

lab-experiment-tracker/app/views/experiments/_edit_results.html.erb
<br>
<%= form_for :experiment, url: experiment_path(experiment), method: :put do |f| %>
  <%= f.text_area :results %><br>
<br>

<%= f.submit "Update Experiment" %>
<% end %>

lab-experiment-tracker/app/views/experiments/_index.html.erb
<center><h2>Experiments</h2></center>
<% experiments.each do |experiment| %>
	<%= link_to experiment.title, experiment_path(experiment) %><br>
<% end %>

<br>
<% if logged_in? && current_user.isScientist == true %>
<center>
	<h4>Add New Experiment</h4>
</center>
	<%= render :partial => 'experiments/new', :locals => {proposal: @proposal} %>
<% end %>

lab-experiment-tracker/app/views/experiments/_new.html.erb
<br>
<div class="container blue darken-4">
<%= form_for :experiment, url: proposal_experiments_path(proposal) do |f| %>
  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :title, :class => "validate" %>
      <label for="title">Title</label>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :results, :class => "validate" %>
      <label for="results">Results</label>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.email_field :conclusion, :class => "validate"%>
      <label for="conclusion">Conclusion</label>
    </div>
  </div>
  <center>
    <%= submit_tag "Submit", :class => "waves-effect waves-light btn" %>
  </center>
  <% end %>
</div>
<br>
<br>

lab-experiment-tracker/app/views/experiments/index.html.erb
<h1>Experiments</h1>
<% @experiments.each do |experiment| %>
	<%= link_to experiment.title, experiment_path(experiment) %><br>
<% end %>

<br>
<h3>Add New Experiment</h3>
<%= render :partial => 'experiments/_new', :locals => {proposal: @proposal} %>

lab-experiment-tracker/app/views/experiments/show.html.erb
<div class="container">
<h2><%= @experiment.title %></h2><br>
Scientist: <%= @experiment.scientist.first_name %>
</div>
<br>

<br>
Procedures:
<ol>
<% @experiment.procedures.order(created_at: :desc).each do |procedure| %>
	<li class="procedure-item"><%= procedure.body %><br></li>
	<%= render partial: 'equipments/index', locals: {procedure: procedure} %>
<% end %>
<br>
<br>
</ol>

Observations:
<% @experiment.observations.each do |observation| %>
	<%= observation.body %><br>
	<% observation.comments.each do |comment| %>
		<%=  comment.body %>
		<%=  comment.user %> <br>
	<% end %><br>

	Add comment to observation
	<%= render partial: 'comments/new', locals: {commentable: observation, comment: Comment.new} %>
<% end %>


<% if logged_in? && current_user.isScientist == true %>
	Add new observation to experiment
	<%= render partial: 'observations/new', locals: {observable: @experiment, observation: Observation.new} %>
<% end %>


<br>
<br>
<% if @experiment.results %>
Results: <%= @experiment.results %><br>
<% end %>

<br>
<br>
<% if @experiment.conclusions %>
Conclusion: <%= @experiment.conclusions %><br>
<% end %>
<br>

<% if logged_in? && current_user.id == @experiment.scientist_id %>
<h3>Add New Procedure</h3>
<%= render :partial => 'procedures/new', :locals => {experiment: @experiment} %>

<% if !@experiment.results %>
<h3>Add Results</h3>
<%= render :partial => 'experiments/edit_results', :locals => {experiment: @experiment} %>
<% end %>

<% if !@experiment.conclusions %>
<h3>Add Conclusions</h3>
<%= render :partial => 'experiments/edit_conclusions', :locals => {experiment: @experiment} %>
<% end %>

<% end %>

Comments:
<br>

<% @experiment.comments.each do |comment| %>
	<%=  comment.body %>
	<%=  comment.user %> <br>
<% end %>


<% if logged_in? == true %>
	Add comment to experiment
	<%= render partial: 'comments/new', locals: {commentable: @experiment, comment: Comment.new} %>
<% end %>

lab-experiment-tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lab Experiment Tracker</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class=" grey darken-1">
  <% if current_user %>
  <nav>
    <div class="nav-wrapper blue darken-4">
      <%= link_to "Home", proposals_path %>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="/users/<%=current_user.id%>" class="waves-effect waves-light btn data-activates="dropdown1"><%=current_user.first_name.upcase%></a></li>
        <li><%= link_to "Logout", '/logout' %></li>
      </ul>
    </div>
  </nav>

  <% else %>
  <nav>
    <div class="nav-wrapper blue darken-4">
      <%= link_to "Home", proposals_path %>
      <ul class="right hide-on-med-and-down">
        <li><%= link_to "Login", '/login' %></li>
        <li><%= link_to "Sign Up", '/signup' %></li>
      </ul>
    </div>
  </nav>
  <% end %>
  <%= yield %>
</body>
</html>

lab-experiment-tracker/app/views/observations/_new.html.haml
= form_for [observable, observation] do |f|
  = f.text_field :body
  = f.submit 'Submit'

lab-experiment-tracker/app/views/procedures/_new.html.erb
<br>
<%= form_for :procedure, url: experiment_procedures_path(experiment) do |f| %>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <%= f.label :equipment %><br>
  <%= f.text_area :equipment %><br>
<br>

<%= f.submit "Create" %>
<% end %>

lab-experiment-tracker/app/views/proposals/_new.html.erb
<div class="container">
<h3>Add a New Proposal:</h3>
<% if @proposal.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@proposal.errors.count, "error") %> prohibited this proposal from being saved:</h2>

    <ul>
    <% @proposal.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="row">

  <%= form_for @proposal, url: proposals_path do |f| %>

    <div class="col s12">
      <div class="row">
        <div class="input-field col s6">
            <%= f.label :summary %>
            <%= f.text_field :summary %><br />
          </div>
        </div>
        <div class="row">
        <div class="input-field col s6">
          <%= f.label :hypothesis %>
          <%= f.text_field :hypothesis %><br />
        </div>
      </div>
      <center>
        <%= submit_tag "Submit", :class => "waves-effect waves-light btn" %>
      </center>
        <% end %>
    </div>
  </div>
</div>

lab-experiment-tracker/app/views/proposals/index.html.erb
<center>
	<h2>Experiment Expert</h2>
</center>
<div class="parallax-container">
	<div class="parallax"><%= image_tag "science-lab-pan.jpg", :class => "responsive-img" %></div>
</div>
<center>
<div class="container">
	<h2>Proposals</h2>
</div>
</center>
<center>
	<div class="center">
		<% @proposals.each do |proposal| %>
		<div class="card-container">
		<div class="row">
			<% if proposal.get_status != "Archived" %>
			<div class="col m6 valign">
				<div class="col m6">
					<div class="card blue-grey darken-1">
						<div class="card-content white-text">
							<span class="card-title">
								Summary: <br><%= link_to proposal.summary, proposal_path(proposal) %></span><br>
								hypothesis:<br>
								<%= proposal.hypothesis %>
							</div>

						</div>
					</div>
				</div>
				<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>
</center>
<br>
<br>
<% if logged_in? && current_user.isScientist == true %>
<div class="container blue darken-4">
	<%= render :partial => 'proposals/new', :locals => {} %>
</div>
<% end %>

lab-experiment-tracker/app/views/proposals/new.html.erb
<h1>Add a New Proposal:</h1>
<% if @proposal.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@proposal.errors.count, "error") %> prohibited this proposal from being saved:</h2>

    <ul>
    <% @proposal.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @proposal do |f| %>
  <%= f.label :summary %>:
  <%= f.text_field :summary %><br />

  <%= f.label :hypothesis %>:
  <%= f.text_field :hypothesis %><br />

  <%= f.submit %>
<% end %>

lab-experiment-tracker/app/views/proposals/show.html.erb
<center>
  <h2><%= @proposal.summary%></h2>
</center>
<br>
<center>
  <div class="card-container row">
    <div class="row">
      <div class="col s8 offset-s2 valign">
        <div class="card-panel blue darken-3">
          <span>
            <h3>Hypothesis <h3>
              <h4><%= @proposal.hypothesis %></h4>
              <h4><font color="orange">Scientist: </font></h4>
              <h5><%= @proposal.user.first_name %> <%= @proposal.user.last_name %></h5>

              <%if @proposal.get_status == "Open"%>
              <font color="orange">Status: </font><span class="cyan"><%= @proposal.get_status %></span>
              <%end%>
              <%if @proposal.get_status == "In progress"%>
              <font color="orange">Status: </font><span class="green lighten-1"><%= @proposal.get_status %></span>
              <%end%>
              <%if @proposal.get_status == "Closed"%>
              <font color="orange">Status: </font><span class="red lighten-1"><%= @proposal.get_status %></span>
              <%end%>
              <%if @proposal.get_status == "Archived"%>
              <font color="orange">Status: </font><span class="purple accent-2"><%= @proposal.get_status %></span>
              <%end%>
            </span>
          </div>
        </div>
      </div>
    </div>
  </center>
<center>
  <div class="container">
    <% if logged_in? && current_user == @proposal.user %>
    <% if @proposal.get_status == "Open" %>
    <%= link_to "Set In Progress", change_status_path(@proposal.id), :class => "waves-effect waves-light btn", method: :put %>
    <% elsif @proposal.get_status == "Closed" %>
    <%= link_to "Archive Proposal",change_status_path(@proposal.id), :class => "waves-effect waves-light btn", method: :put %>
    <% elsif @proposal.get_status == "In progress" %>
    <%= link_to "Close Proposal", change_status_path(@proposal.id), :class => "waves-effect waves-light btn", method: :put %>
    <% end %>
    <% end %>
  </center>
    <br>
    <br>
  </div>
  <div class="container cyan lighten-1">
    <div class="row">
      <div class="col s4">
        <h3>Comments:</h3>
        <br>
        <% @proposal.comments.each do |comment| %>
        <h5><%=  comment.body %></h5><br>
        <div class="row">
          <div class="col s3">
            <div class="chip orange lighten-2">
              <%= comment.user.first_name %>
              <%= comment.user.last_name %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<center>
  <h5>Add comment to proposal</h5>
</center>
<%= render partial: 'comments/new', locals: {commentable: @proposal, comment: Comment.new} %>

<%= render :partial => 'experiments/index', :locals => {experiments: @proposal.experiments, proposal: @proposal} %>

lab-experiment-tracker/app/views/users/new.html.erb
<div class="container">
  <h2>Sign Up</h2>
</div>

<div class="container blue darken-4">
  <%= form_for :user, url: '/users' do |f| %>
  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :first_name, :class => "validate" %>
      <label for="first_name">First Name</label>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :last_name, :class => "validate" %>
      <label for="last_name">Last Name</label>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.check_box :isScientist, :class => "filled-in", :id => "Are you a scientist?" %>
      <label for="Are you a scientist?">Are you a scientist?</label>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.email_field :email, :class => "validate"%>
      <label for="email" data-error="wrong" data-success="right">Email</label>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.password_field :password, :class => "validate" %>
      <label for="password" >Password</label>
    </div>
  </div>
  <center>
    <%= submit_tag "Submit", :class => "waves-effect waves-light btn" %>
  </center>
  <% end %>
</div>

lab-experiment-tracker/app/views/users/show.html.erb
<h1>hi</h1>